---
title: scRNAseq analysis plots
author: "Jan Gleixner, Maja Funk"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    code_folding: hide
    keep_md: true
params:
  aggregated_data_dir: "processed_data"
  processed_data_dir: "processed_data"
  raw_data_dir: "raw_data"
  differential_expression_dir: "processed_data"
  meta_data_dir: "analysis_pipeline"
  results_dir: "results"
---
``` {r attach packages , warn=FALSE, message=FALSE, echo=FALSE}
library(Seurat)
library(schelpr)

library(data.table)
library(ggplot2)
library(patchwork)
library(grid)
```

```{r do setup, code=readLines(fs::path(rprojroot::find_rstudio_root_file(), "setup_chunk.R")), echo=FALSE, eval=TRUE, collapse=TRUE, }
source(file = fs::path(rprojroot::find_rstudio_root_file(), "setup_chunk.R")) # needed if run interactively in RStudio
```

```{r load helper functions, code=readLines(fs::path(rprojroot::find_rstudio_root_file(), "helper_functions_and_colors.R")), echo=TRUE, eval=TRUE, class.source = 'fold-hide'}
source(file = fs::path(rprojroot::find_rstudio_root_file(), "helper_functions_and_colors.R")) # needed if run interactively in RStudio
```

```{r load cell meta data}
dt <- fread(fs::path(processed_data_dir, "meta_and_reductions.tsv.gz"), sep= "\t")
dt[,cell[1], by = sample_name][, stopifnot(all.equal(order(V1), order(sample_name)))] %>% invisible() # ensure that cell and samples match
```

```{r load count data and merge with cell meta data to create seurat object}
dirs <- fs::path_dir( fs::dir_ls(raw_data_dir, regexp = "matrix.mtx.gz", recurse = TRUE))
som <- Seurat::Read10X(dirs)
so <- Seurat::CreateSeuratObject(som, meta.data = data.frame(dt, row.names = dt$cell))
so <- so[, !is.na(so$cell)]
```

```{r normalize}
so %<>% Seurat::NormalizeData()
```

```{r marker gene and score tSNE plots, fig.height=18, fig.width=9}
example_marker_genes <- c("Stem cells" = "Olfm4", "Paneth cells" = "Defa24", "Goblet cells" = "Muc2", "Enteroendocrine cells" = "Chgb", "Enterocytes" = "Fabp1", "Tuft cells" = "Dclk1")
cell_type_labels <- c("Stem cells" = "Stem", "Paneth cells" = "Paneth", "Goblet cells" = "Goblet", "Enteroendocrine cells" = "EEC", "Enterocytes" = "Enterocyte", "Tuft cells" = "Tuft")


expression_dt <- as.data.table((exp(Matrix::t(Seurat::GetAssayData(so)[example_marker_genes,]))-1)*1E6/1E4 , keep.rownames = "cell" )
dt <- expression_dt[dt, on = "cell"]

p_gene_s <- lapply(example_marker_genes, function(gene) {
  dt %>% ggplot(aes_string(x = "tSNE_1", y = "tSNE_2", color = gene)) + geom_cell() +  schelpr::scale_color_log1p_scaled(scale=1/100, name = paste0(gene, "\n[CPM]"))
})


p_score_s <- lapply(names(example_marker_genes), function(cell_type) {
  dt %>% ggplot(aes_string(x = "tSNE_1", y = "tSNE_2", color = paste0("`", cell_type, "`"))) + geom_cell() + scale_color_continuous(stringr::str_wrap(paste0(cell_type_labels[cell_type], " score"), 12)) #my_wrap(cell_type))
})

p_name_s <- lapply(names(example_marker_genes), function(cell_type) {
  wrap_elements(plot=grobTree(rectGrob(gp=gpar(col= 'black')), textGrob(cell_type, rot = 90)), clip = TRUE) 
})

wrap_plots(c(p_name_s, p_gene_s, p_score_s), ncol = 3, byrow=FALSE, widths = c(0.13, 1, 1)) + plot_annotation(tag_levels = list(c(letters[seq_along(p_name_s)],character(length(p_name_s)*2))))  

```

```{r marker gene and score umap plots, fig.height=18, fig.width=9}
example_marker_genes <- c("Stem" = "Olfm4", "Enterocyte.Mature.Proximal" = "Fabp1","Endocrine" = "Chgb", "Paneth" = "Defa24", "Goblet" = "Muc2",  "Tuft" = "Dclk1")
cell_type_labels <- c("Stem" = "Stem", "Paneth" = "Paneth", "Goblet" = "Goblet", "Endocrine" = "EEC", "Enterocyte.Mature.Proximal" = "Enterocyte", "Tuft" = "Tuft")
cell_type_labels2 <- c("Stem" = "Stem cells", "Paneth" = "Paneth cells", "Goblet" = "Goblet cells", "Endocrine" = "EECs", "Enterocyte.Mature.Proximal" = "Enterocytes", "Tuft" = "Tuft cells")

expression_dt <- as.data.table((exp(Matrix::t(Seurat::GetAssayData(so)[example_marker_genes,]))-1)*1E6/1E4 , keep.rownames = "cell" )
dt <- expression_dt[dt, on = "cell"]

p_gene_s <- lapply(example_marker_genes, function(gene) {
  dt %>% ggplot(aes_string(x = "tSNE_1", y = "tSNE_2", color = gene)) + geom_cell() + schelpr::scale_color_log1p_scaled(scale=1/100, name = paste0(gene, "\n[CPM]"))
})
p_score_s <- lapply(names(example_marker_genes), function(cell_type) {
  dt %>% ggplot(aes_string(x = "tSNE_1", y = "tSNE_2", color = paste0("`prediction.score.", cell_type, "`"))) + geom_cell() + scale_color_continuous(stringr::str_wrap(paste0(cell_type_labels[cell_type], " score"), 12))
})

p_name_s <- lapply(names(example_marker_genes), function(cell_type) {
  wrap_elements(plot=grobTree(rectGrob(gp=gpar(col= 'black')), textGrob(cell_type_labels[cell_type], rot = 90)), clip = TRUE) 
})

wrap_plots(c(p_name_s, p_gene_s, p_score_s), ncol = 3, byrow=FALSE, widths = c(0.13, 1, 1)) + plot_annotation(tag_levels = list(c(letters[seq_along(p_name_s)],character(length(p_name_s)*2))))  

```
























