---
title: "Ageing & Wnt in an organoid model of the mouse small instenial stem cell niche - integration"
author: "Jan Gleixner, Maja Funk"
date: "`r Sys.Date()`"
params:
  processed_data_dir:  "results_ci_human/analysis_untreated/0_qc_filtering"
  results_dir: "results"
  haber_so_dir: "results_ci_human/analysis_untreated/0_prepare_Haber_data"
---

```{r do setup, code=readLines(fs::path(rprojroot::find_rstudio_root_file(), "notebooks", "setup_chunk.R")), echo=FALSE, eval=TRUE}
source(file = fs::path(rprojroot::find_rstudio_root_file(), "notebooks", "setup_chunk.R")) # for RStudio
```

``` {r, warn=FALSE, message=FALSE, echo=FALSE}
library(Matrix.utils)
library(Seurat)
library(dplyr)

library(sir)

library(data.table)
library(tidyverse)

```

```{r load  gene list}
cell_types_dt <- fread("SI_cell_type_markers.tsv")[marker_gene_symbol!=""]
cell_types_list <- lapply(split(cell_types_dt, by="cell_type"), `[`, , marker_gene_symbol)

features_dt <- fread("SI_feature_gene_lists.tsv")[marker_gene_symbol!=""]
features_list <- lapply(split(features_dt, by="feature"), `[`, , marker_gene_symbol)
```

```{r load haber data}
haber_so <- read_rds( fs::path(haber_so_dir, "seurat_object.rds"))
```

```{r}
si <- read_rds(fs::path(processed_data_dir, "seurat_object.rds"))

sis <- SplitObject(si, split.by = "Tx_run_number")
DefaultAssay(haber_so) <- "RNA"
haber_sos <- SplitObject(haber_so, split.by = "sample_name")
anchors <- FindIntegrationAnchors(object.list = c(haber_sos, sis), reference = 1)
si.integrated <- IntegrateData(anchorset = anchors,  new.assay.name = "integrated2")
```

```{r scale and run pca and umap}
si.integrated %<>% ScaleData()
si.integrated %<>% RunPCA()
si.integrated %<>% RunTSNE(dims = 1:10)
```

```{r plot embedding}
si.integrated %>% DimPlot(group.by = "sample_name", split.by = "Tx_run_number")
si.integrated %>% DimPlot(group.by = "Tx_run_number")
```

```{r}
mm <- si.integrated %>% schelpr::meta_and_reductions()
mm_wo_facet <- copy(mm)[, c("sample_name", "Tx_run_number", "condition", "treatment") := NULL]
mm
```


```{r}
for (cell_type in paste0("`",names(cell_types_list), "`")) {
  p1 <- mm %>% ggplot(aes_string(x="tSNE_1", y="tSNE_2", color=cell_type)) + 
      geom_cell(data=mm_wo_facet, color="gray") + 
      geom_cell() + 
      facet_grid(.~Tx_run_number)
    p1 %>% print()
}
```

```{r}
 mm %>% ggplot(aes_string(x="tSNE_1", y="tSNE_2", color="sample_name")) + 
      geom_cell(data=mm_wo_facet, color="gray") + 
      geom_cell() + 
      facet_grid(.~Tx_run_number)
```

```{r}
 mm %>% ggplot(aes_string(x="tSNE_1", y="tSNE_2", color="treatment")) + 
      geom_cell(data=mm_wo_facet, color="gray") + 
      geom_cell() + 
      facet_grid(.~Tx_run_number)

 mm %>% ggplot(aes_string(x="tSNE_1", y="tSNE_2", color="condition")) + 
      geom_cell(data=mm_wo_facet, color="gray") + 
      geom_cell() + 
      facet_grid(.~Tx_run_number)
```

```{r save integerated seurat object for use in downstream analysis}
write_rds(si.integrated, fs::path(results_dir,"seurat_object.rds"))
```
