---
title: "Ageing & Wnt in an organoid model of the mouse small intestinal stem cell niche - composition"
author: "Jan Gleixner, Maja Funk"
date: "`r Sys.Date()`"
params:
  processed_data_dir: "results_ci_human/analysis_in_vivo/2_cell_type_assignment"
  results_dir: "results"
---

```{r do setup, code=readLines(fs::path(rprojroot::find_rstudio_root_file(), "notebooks", "setup_chunk.R")), echo=FALSE, eval=TRUE}
source(file = fs::path(rprojroot::find_rstudio_root_file(), "notebooks", "setup_chunk.R")) # for RStudio
```

``` {r, warn=FALSE, message=FALSE, echo=FALSE}
library(Matrix.utils)
library(Seurat)
library(dplyr)

library(sir)

library(data.table)
library(tidyverse)
```

```{r}
mm <- fread(fs::path(processed_data_dir,"meta_and_reductions.tsv"))
mm[1:2,]
```

```{r cell type composition}
summary_dt <- mm[, .N, by=.(cell_type, sample_name)]
summary_dt <- summary_dt[CJ(cell_type=unique(cell_type), sample_name=unique(sample_name)), on = .(cell_type, sample_name)]

summary_dt[is.na(N), N:=0]
summary_dt <- unique(mm[, .(sample_name, treatment, condition, sample_type, Tx_run_number)])[summary_dt, on = .(sample_name)]
summary_dt[, N_sample := sum(N), by=sample_name]
summary_dt[, fraction_of_sample := N/N_sample]

p1 <- summary_dt %>% ggplot(aes(x=cell_type, y=fraction_of_sample, color=condition, shape=condition, group=condition)) + 
  geom_point(position=position_dodge(0.5)) +
  facet_wrap(vars(sample_type), ncol=3) + 
  expand_limits(y=0) +
  scale_y_continuous(labels=scales::percent) +
  guides(x = guide_axis(angle = 90)) +
  sir::scale_color_age() +
  sir::scale_x_cell_type() +
 # geom_line(position=position_dodge(0.5),color=)
  NULL
p1
                   
summary_dt %>% ggplot(aes(x=condition, y=fraction_of_sample, color=condition, shape=condition, group=Tx_run_number)) + 
  expand_limits(y=0) +
  scale_y_continuous(labels=scales::percent) +
  guides(x = guide_axis(angle = 45)) +
  sir::scale_color_age() +
  geom_line(color="black") +
  geom_point() +
  facet_wrap(vars(cell_type), nrow=2, scales = "free_y") +
  NULL
```


```{r plot cell types across samples, fig.width=15.4, fig.height=3.5}
library(ggnewscale)
ggplot(summary_dt, aes(x=condition, y=fraction_of_sample)) +
  scale_y_continuous(labels = scales::percent_format(1),
                     breaks = function(x) seq(0, ceiling(x[2]/0.050))*0.050) + #, expand = expand_scale(add=c(0.01,0.05))
  facet_grid(Tx_run_number ~cell_type, scales="free", space="free_x") +
  geom_col(aes(y=Inf, fill = condition), alpha=0.3, width=1) +
  sir::scale_fill_age() +
  # ----------
  new_scale("fill") +
  geom_col(aes(fill = cell_type), position = position_dodge(), width=0.66) +
  geom_blank(data=copy(summary_dt)[, fraction_of_sample:=0.08]) +
  coord_flip() +
  sir::scale_fill_cell_type() +
  theme(#axis.title.y=element_blank(),
        #axis.text.y=element_blank(),
        #axis.ticks.y=element_blank(),
        aspect.ratio=NULL#1/4
        ) +
  NULL


ggplot(summary_dt, aes(x=as.factor(Tx_run_number), y=fraction_of_sample)) +
  scale_y_continuous(labels = scales::percent_format(1),
                     breaks = function(x) seq(0, ceiling(x[2]/0.050))*0.050) + #, expand = expand_scale(add=c(0.01,0.05))
  facet_grid(condition ~cell_type, scales="free", space="free_x") +
  geom_col(aes(y=Inf, fill = condition), alpha=0.3, width=1) +
  sir::scale_fill_age() +
  # ----------
  new_scale("fill") +
  geom_col(aes(fill = cell_type), position = position_dodge(), width=0.66) +
  geom_blank(data=copy(summary_dt)[, fraction_of_sample:=0.08]) +
  coord_flip() +
  sir::scale_fill_cell_type() +
  geom_label(data = summary_dt[fraction_of_sample<0.05], aes(label=N, y = fraction_of_sample+0.01), position=position_dodge2(reverse=TRUE, width=0.9), size=3, hjust = 0) +
  geom_label(data = summary_dt[fraction_of_sample>=0.05], aes(label=N, y = fraction_of_sample-0.01), position=position_dodge2(reverse=TRUE, width=0.9), size=3, hjust = 1) +
  theme(axis.title.y=element_blank(),
        #axis.text.y=element_blank(),
        #axis.ticks.y=element_blank(),
        aspect.ratio=NULL#1/4
        ) +
  NULL
```


## Cell cycle across samples/celltypes/both
g2m and s phase scores are combined (sum) into a proliferation score (larger value: more proliferation) and plotted across samples, celltypes and both

```{r plot proliferation score over samples}
mm %>% group_by(cell_type) %>% summarise_at(vars(ccs,ccg2m), mean)

mm %>% 
  group_by(condition, treatment, sample_name, mouse) %>% 
  summarise(proliferation_score=mean(ccs)+mean(ccg2m)) %>% 
  ggplot(aes(x=sample_name, y=proliferation_score, color= condition, group=mouse)) + 
    geom_point(size=5) +
  sir::scale_color_age() +
  geom_line()+
  coord_flip()

mm[, proliferation_score := ccs+ccg2m] 
mm %>%  
  ggplot(aes(x=condition, y=proliferation_score, color= cell_type, group = sample_name)) + 
  ggrastr::rasterize(ggforce::geom_sina()) +
  ggfx::with_shadow(stat_summary(position=position_dodge(1)), x_offset = 3, y_offset = 3, sigma = 3) +
  sir::scale_color_cell_type() +
  sir::scale_x_age() +
  facet_wrap(vars(cell_type), nrow= 2) +
  coord_flip()

mm  %>% 
  group_by(cell_type, condition, treatment, sample_name, mouse) %>% 
  summarise(proliferation_score=mean(ccs)+mean(ccg2m)) %>% 
  ggplot(aes(x=cell_type, y=proliferation_score, color= condition, group = condition)) + 
    geom_point(position= position_dodge(width=0.5)) +
  stat_summary(geom="errorbar", aes(color = stage(condition, after_scale = colorspace::darken(color, 0.4))), width=0.5, position= position_dodge()) +
  stat_summary(geom="point", aes(color = stage(condition, after_scale = colorspace::darken(color, 0.4))),width=0.5, position= position_dodge(width=0.5),size=4, shape="diamond") +
  sir::scale_color_age() +
  sir::scale_x_cell_type() +
  coord_flip()
```

```{r}
summary_dt[, broom::tidy(t.test((fraction_of_sample)~condition, data = .SD)), by = cell_type]
summary_dt[, broom::tidy(t.test(log(fraction_of_sample+0.1)~condition, data = .SD)), by = cell_type][, adj_pval := p.adjust(p.value, method = "BH")][]
count_mat_dt <- dcast(summary_dt, sample_name + condition  + Tx_run_number ~ cell_type, value.var = c("N") )
count_data <- t(as.matrix(count_mat_dt[, -(1:3)]))
col_data <- count_mat_dt[, 1:3]
col_data[, Tx_run_number := as.factor(Tx_run_number)]
```


```{r}
library(DESeq2)
deseq_obj <- DESeq2::DESeqDataSetFromMatrix(countData = count_data, colData = col_data, design = ~condition)
sizeFactors(deseq_obj) <- colSums(count_data)/mean(colSums(count_data))
dp_dt <- data.table(data.frame(DESeq2::results(DESeq2::DESeq(deseq_obj, fitType = "mean"), name = "condition_young_vs_aged")), keep.rownames = "cell_type")
dp_dt

effect_size_plot <- function(dt, alpha = 0.95) ggplot(dt, aes(x= cell_type, y= -log2FoldChange)) +
  geom_errorbar(aes(ymin=-log2FoldChange-lfcSE*qnorm(1-(1-alpha)/2),ymax=-log2FoldChange+lfcSE*qnorm(1-(1-alpha)/2))) +
  geom_point(aes(color=cell_type), size= 3) +
  sir::scale_x_cell_type() +
  sir::scale_color_cell_type(guide = "none")
#
dp_dt %>% effect_size_plot()
```

```{r batch adjusted}
if(length(unique(col_data$Tx_run_number)) > 1) {
  deseq_obj <- DESeq2::DESeqDataSetFromMatrix(countData = count_data, colData = col_data, design = ~condition + Tx_run_number)
  sizeFactors(deseq_obj) <- colSums(count_data)/mean(colSums(count_data))
  dp_paired_dt <- data.table(data.frame(DESeq2::results(DESeq2::DESeq(deseq_obj, fitType = "mean"), name = "condition_young_vs_aged")), keep.rownames = "cell_type")
  
  alpha <- 0.95
  dp_paired_dt[, upper_95_ci_percentage_point_change := max(abs(log2FoldChange+ c(-1,1)*lfcSE*qnorm(1-(1-alpha)/2))), by= cell_type]
  print(dp_paired_dt[][])
  
  dp_paired_dt %>% effect_size_plot()
}
```

```{r}
if(length(unique(col_data$Tx_run_number)) > 1) {
  summary_wide_dt <- dcast(summary_dt, cell_type  + Tx_run_number ~ condition, value.var = c("fraction_of_sample", "N") )
  summary_wide_dt
  paired_t_test_res <- summary_wide_dt[, broom::tidy(t.test(fraction_of_sample_young, fraction_of_sample_aged, paired=TRUE)), by = cell_type
             ][, .(absolute_change_fraction_ci = pmax(abs(conf.low), abs(conf.high)), conf.low, conf.high, pval = p.value), keyby = cell_type
               ][, adj_pval := p.adjust(pval, method = "BH")][]
  paired_t_test_res[, upper_95_ci_percentage_point_change := scales::percent(max(abs(c(conf.low, conf.high)))), by= cell_type][]
  paired_t_test_res
}
```





```{r, eval = FALSE, include =FALSE}
lm_res_dt <- summary_dt[, broom::tidy(summary(lm(fraction_of_sample ~ condition + Tx_run_number, .SD))), by=cell_type][term=="conditionyoung"]
lm_res_dt

glm_res_dt <- summary_dt[, broom.mixed::tidy((lme4::glmer(cbind(N, N_sample-N) ~ condition + (1|Tx_run_number) +(1|sample_name), .SD, family = "binomial"))), by=cell_type][term=="conditionyoung"]
glm_res_dt
```

```{r}
summary_dt[, broom::tidy(summary(lm(fraction_of_sample ~ condition, .SD))), by=cell_type][term=="conditionyoung"]
summary_dt[, broom::tidy(t.test((fraction_of_sample)~condition, data = .SD)), by = cell_type]
```
```{r}
if(length(unique(col_data$Tx_run_number)) > 1) {
  summary_wide_dt[, broom::tidy(t.test(fraction_of_sample_young, fraction_of_sample_aged, paired=TRUE)), by = cell_type]
  summary_dt[, broom::tidy(summary(lm(fraction_of_sample ~ condition + Tx_run_number, .SD))), by=cell_type][term=="conditionyoung"]
  summary_wide_dt[, broom::tidy(summary(lm(fraction_of_sample_young-fraction_of_sample_aged ~ 1, .SD))), by=cell_type]
}
```
