---
title: Ageing & Wnt in an organoid model of the mouse small instenial stem cell niche
  - analysis
author: "Jan Gleixner, Maja Funk"
date: "`r Sys.Date()`"
params:
  only_untreated: !r FALSE
  aggregated_data_dir: "results_ci_human/analysis_in_vivo/3_aggregation"
  results_dir: "results"
---

```{r do setup, code=readLines(fs::path(rprojroot::find_rstudio_root_file(), "notebooks", "setup_chunk.R")), echo=FALSE, eval=TRUE}
source(file = fs::path(rprojroot::find_rstudio_root_file(), "notebooks", "setup_chunk.R")) # for RStudio
```


``` {r, warn=FALSE, message=FALSE, echo=FALSE}
library(Matrix.utils)
library(Seurat)
library(dplyr)

library(sir)
library(schelpr)

library(data.table)
library(tidyverse)
```

```{r}
meta_dt <- fread("Sample meta - Sheet1.tsv")
setkey(meta_dt, key="sample_id")
meta_dt[, Tx_run_number := factor(Tx_run_number)][]
meta_dt
```


```{r load aggregated data}
agg_dt <- fread(file = fs::path(aggregated_data_dir, "aggregated_expression.tsv"), sep = "\t")
agg_dt[, Tx_run_number := factor(Tx_run_number)][]
```

```{r mhcII pval}
mhcII_features_dt <- fread("SI_feature_gene_lists.tsv")[feature %in% "MHC class II"]
mhcII_features_dt <- agg_dt[mhcII_features_dt, on = .(gene = marker_gene_symbol)]
```

```{r, fig.height = 3.5, fig.width = 9}
this_dodge <- position_dodge(width=0.2)
mhcII_features_dt %>% ggplot(aes(x = cell_type, y = CPM, ymin = CPM_lower, ymax = CPM_upper, color = condition, group = interaction(cell_type, Tx_run_number))) +
  geom_point(aes(shape = Tx_run_number), size = 2, position = this_dodge) +
  geom_errorbar(width = 0.3, position = this_dodge) +
  geom_line(aes(group = sample_id, linetype = Tx_run_number), position = this_dodge) +
  scale_x_cell_type() +
  facet_wrap("gene", scales = "free_y", nrow = 2) +
  scale_y_log1p() +
  scale_color_age() +
  theme(aspect.ratio = 2/3) +
  NULL
ggsave(filename = "results/mchIIexpression.png", dpi = 600, height = FIG_HEIGHT, width = FIG_HEIGHT*3)
```




